name: Go
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache-dependency-path: go.mod
      - uses: actions/checkout@v2
      - run: go get -t ./...
      - run: go build -v ./...
      - run: go test -v ./...
